### ISSUE TITLE
medications.html

### ISSUE THREAD

**Issue by jessicamvs** [tlesavage/medication_app_final_project#2]
System will provide a Medications List within the site.  

Medications List will provide:
- Title
- List of all medications
- Add New Medication indicator
- Delete Medication indicator
- Disclaimer instructing the user to take all medications as per their prescribing physician's instructions.  

For each medicaiton listed within the Medicaiton List view, the system will display:
- Medication Name
- Dosage
- Dosage Type (mg, oz, etc)
- Number of pills remaining
- Number of refils remaining

**Comment by spamalope01** [comment]
Added all HTML for this page.  table will be created dynamically with JS on page load.
