### ISSUE TITLE
addmed.html

### ISSUE THREAD

**Issue by jessicamvs** [tlesavage/medication_app_final_project#3]
System will provide an Add New indicator within the Medications List view.  Selection of this indicator will display the Add New Medication view.

Add New Medication will provide:
- Title
- Save indicator
- Back/Cancel indicator
- Med Name field
- Prescribing Doctor Name field
- Dosage field
- Dosage type selector
- Quanity in Prescription field
- Start Date field
- Duration of Prescription indicator (as needed, or until gone, etc)
- Intervals selector (every day, every other day, etc)
- First Time Taken field
- Second Time Taken field
- Third Time Taken field
- With Food selector
- Before Food selector
- Number of Refills field
- Pharmacy Name field
- Pharmacy Phone field
- No Longer Taking This indicator
- Add to current schedule indicator
- Additional Notes field

The following fields will be required:
- Med Name
- Start Date
- Dosage
- Intervals
- First Time Taken
- Number Taken
- Food Instructions

Selection of the Save indicator will add the newly entered medication to the Medicaiton List view, and return the user to the Medication List view.  

Selection of the Cancel indicator will return the user to the Medication List view and not save any information.

**Comment by spamalope01** [comment]
Created all HTML for this page.
